name: Deploy in Surge
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: deploy on surge
        run: |
          npm run build
          npm install -g surge
          surge ./dist poc-proto-recording.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        env:
          CI: true
